name: Node CI

on: 
  push:
    branches:
    - staging
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        yarn install
        npm run build --if-present
      env:
        CI: true
    - name: Webhook
      if: success()
      uses: ybrin/secure-actions-webhook@0.1.2
      env:
        REQUEST_URI: ${{ secrets.WEBHOOK_URL }}
        REQUEST_DATA: '{ "key1": ${{secrets.GUID}} }'
        HMAC_SECRET: "secret_used_to_generate_signature"
